# Generated by Django 4.0 on 2023-10-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0003_alter_temporaryproduct_data'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='TemporaryPreProduct',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('Parsers1', models.CharField(max_length=255, verbose_name='Парсер')),
        #         ('data', models.TextField(max_length=255, verbose_name='Название')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
        #         ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
        #     ],
        # ),
    ]
