# Generated by Django 4.0 on 2023-10-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0005_temporarypreproduct_maked_temporaryproduct_maked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryproduct',
            name='maked',
            field=models.BooleanField(default=False, null=True, verbose_name='Обработано'),
        ),
    ]
