# Generated by Django 4.0 on 2023-10-17 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0007_product_product_full_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город (парсера)', 'verbose_name_plural': 'Города (парсеров)'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='Parsers1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.Parsers1', verbose_name='Парсер'),
        ),
        migrations.AlterField(
            model_name='Parsers1',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Внутренний код'),
        ),
        migrations.AlterField(
            model_name='Parsers1',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='UniqueCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='MergedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.city', verbose_name='Город (парсера)')),
                ('unique_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.uniquecity', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'МультиГород',
                'verbose_name_plural': 'МультиГород',
            },
        ),
    ]
