# Generated by Django 4.0 on 2023-10-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0009_alter_field_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='Parsers1',
        ),
    ]
