# Generated by Django 4.0 on 2023-10-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0010_remove_city_city_name_remove_city_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внутренний код'),
        ),
        migrations.AddField(
            model_name='city',
            name='Parsers1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.Parsers1', verbose_name='Парсер'),
        ),
        migrations.AlterField(
            model_name='field',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внутренний код'),
        ),
        migrations.AlterField(
            model_name='Parsers1',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внутренний код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внутренний код'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внутренний код'),
        ),
    ]
