# Generated by Django 4.0 on 2023-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0014_mappingcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercity',
            name='not_a_city',
            field=models.BooleanField(default=False),
        ),
    ]
