# Generated by Django 4.0 on 2023-10-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0015_suppliercity_not_a_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercity',
            name='not_a_city',
        ),
        migrations.AddField(
            model_name='city',
            name='not_a_city',
            field=models.BooleanField(default=False),
        ),
    ]
