# Generated by Django 4.0 on 2023-11-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0016_remove_suppliercity_not_a_city_city_not_a_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_count', models.IntegerField(null=True, verbose_name='Количество поставщиков')),
                ('categories_count', models.IntegerField(null=True, verbose_name='Количество категорий')),
                ('products_count', models.IntegerField(null=True, verbose_name='Количество продуктов')),
                ('cities_count', models.IntegerField(null=True, verbose_name='Количество городов')),
                ('fields_count', models.IntegerField(null=True, verbose_name='Количество полей')),
                ('pre_count', models.IntegerField(null=True, verbose_name='Количество сырых товаров')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('Parsers1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.Parsers1', verbose_name='Парсер')),
            ],
            options={
                'verbose_name': 'Статистика сайта',
                'verbose_name_plural': 'Статистики сайтов',
            },
        ),
    ]
