# Generated by Django 4.0 on 2023-11-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0017_parserstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAIN', 'Главная'), ('CITY', 'Город')], default='MAIN', max_length=16, verbose_name='Тип')),
                ('products_count', models.IntegerField(null=True, verbose_name='Количество продуктов')),
                ('categories_count', models.IntegerField(null=True, verbose_name='Количество категорий')),
                ('suppliers_count', models.IntegerField(null=True, verbose_name='Количество поставщиков')),
                ('cities_count', models.IntegerField(null=True, verbose_name='Количество городов')),
                ('parsers_count', models.IntegerField(null=True, verbose_name='Количество сайтов')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
