# Generated by Django 4.0 on 2023-11-01 07:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0020_btree'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['product_full_text'], name='metinvest_d_product_db350a_gin'),
        ),
    ]
