# Generated by Django 4.0 on 2023-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0023_alter_product_product_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='json_view',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='json_view',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
