# Generated by Django 4.0 on 2023-11-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0026_statistics_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hash_with_price',
            field=models.CharField(max_length=65, null=True, verbose_name='Хэш с ценой'),
        ),
        migrations.AddField(
            model_name='product',
            name='hash_without_price',
            field=models.CharField(max_length=65, null=True, verbose_name='Хэш без цены'),
        ),
    ]
