# Generated by Django 4.0 on 2023-11-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0028_product_parsed_alter_product_hash_with_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Parsers1',
        ),
    ]
