# Generated by Django 4.0 on 2023-11-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0029_remove_city_parser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='not_a_city',
        ),
        migrations.AddField(
            model_name='city',
            name='Parsers1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.Parsers1', verbose_name='Парсер'),
        ),
    ]
