# Generated by Django 4.0 on 2023-11-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0033_alter_temporaryproduct_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEncodingSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utf_value', models.CharField(max_length=255, verbose_name='Оригинал')),
                ('replace_with_value', models.CharField(max_length=255, verbose_name='Замена')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Непереводимый символ',
                'verbose_name_plural': 'Непереводимые символы',
            },
        ),
    ]
