# Generated by Django 4.0 on 2023-11-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0035_metinvestmanager_uniquesupplier_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquesupplier',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('schedule', models.CharField(blank=True, max_length=255, null=True, verbose_name='График работы')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('unique_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metinvest_database.uniquesupplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
