# Generated by Django 4.0 on 2023-11-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0037_delete_mappingcity_delete_mergedcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.uniquesupplier', verbose_name='Поставщик'),
        ),
    ]
