# Generated by Django 4.0 on 2023-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0039_alter_office_address_alter_office_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
