# Generated by Django 4.0 on 2023-10-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0002_category_city_mergedcategory_mergedproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryproduct',
            name='data',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
    ]
