# Generated by Django 4.0 on 2023-10-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0006_alter_temporaryproduct_maked'),
    ]

    operations = [
    #     migrations.AddField(
    #         model_name='product',
    #         name='product_full_text',
    #         field=models.TextField(null=True),
    #     ),
    ]
