# Generated by Django 4.0 on 2023-10-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0008_alter_city_options_remove_city_region_city_city_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('Parsers1', 'code')},
        ),
    ]
