# Generated by Django 4.0 on 2023-10-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0011_city_city_name_city_code_city_parser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='unique_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.uniquecity', verbose_name='Город'),
        ),
        migrations.DeleteModel(
            name='MergedCity',
        ),
    ]
