# Generated by Django 4.0 on 2023-10-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0012_city_unique_city_delete_mergedcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='changed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='uniquecity',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.region', verbose_name='Регион'),
        ),
    ]
