# Generated by Django 4.0 on 2023-10-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0013_product_changed_alter_uniquecity_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='Название города')),
                ('code', models.CharField(max_length=255, verbose_name='Обозначение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Маппинг города',
                'verbose_name_plural': 'Маппинги городов',
            },
        ),
    ]
