# Generated by Django 4.0 on 2023-11-01 07:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0019_product_search_vector_and_more'),
    ]

    operations = [
        BtreeGinExtension()
    ]
