# Generated by Django 4.0 on 2023-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0021_product_metinvest_d_product_db350a_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_full_text',
            field=models.TextField(null=True),
        ),
    ]
