# Generated by Django 4.0 on 2023-11-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0022_alter_product_product_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_full_text',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
