# Generated by Django 4.0 on 2023-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0024_category_json_view_product_json_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='not_a_city',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
