# Generated by Django 4.0 on 2023-11-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0025_alter_city_not_a_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='foreign_id',
            field=models.IntegerField(null=True),
        ),
    ]
