# Generated by Django 4.0 on 2023-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0027_product_hash_with_price_product_hash_without_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parsed',
            field=models.DateTimeField(null=True, verbose_name='Последний парсинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hash_with_price',
            field=models.CharField(db_index=True, max_length=65, null=True, verbose_name='Хэш с ценой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hash_without_price',
            field=models.CharField(db_index=True, max_length=65, null=True, verbose_name='Хэш без цены'),
        ),
    ]
