# Generated by Django 4.0 on 2023-11-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0030_remove_city_city_name_remove_city_not_a_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergedSupplier',
            new_name='UniqueSupplier',
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик (парсера)', 'verbose_name_plural': 'Поставщики (парсеров)'},
        ),
        migrations.AlterModelOptions(
            name='uniquesupplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
