# Generated by Django 4.0 on 2023-11-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0031_rename_mergedsupplier_uniquesupplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquesupplier',
            name='code',
            field=models.CharField(default=None, max_length=255, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
