# Generated by Django 4.0 on 2023-11-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0032_uniquesupplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryproduct',
            name='data',
            field=models.TextField(max_length=255, verbose_name='Данные'),
        ),
    ]
