# Generated by Django 4.0 on 2023-11-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('metinvest_database', '0034_errorencodingsymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetinvestManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь системы')),
            ],
        ),
        migrations.AddField(
            model_name='uniquesupplier',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RatingScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.metinvestmanager', verbose_name='Оценивший менеджер')),
            ],
            options={
                'verbose_name': 'Оценка рейтинга',
                'verbose_name_plural': 'Оценки рейтингов',
            },
        ),
    ]
