# Generated by Django 4.0 on 2023-11-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metinvest_database', '0036_uniquesupplier_comment_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MappingCity',
        ),
        migrations.DeleteModel(
            name='MergedCategory',
        ),
        migrations.DeleteModel(
            name='MergedProduct',
        ),
        migrations.AlterField(
            model_name='office',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metinvest_database.uniquesupplier', verbose_name='Поставщик'),
        ),
    ]
