# Generated by Django 5.0.4 on 2024-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
            ],
            options={
                'unique_together': {('charcode', 'date')},
            },
        ),
    ]
